# Generated by Django 3.1.14 on 2022-03-01 17:06

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220301_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_software',
            name='admin_usuarios',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Tiene esquema de administración de usuarios?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='auditoria',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Tiene esquema de auditorías? '),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='criterios',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Aplica criterios de usabilidad y accesibilidad? '),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='firewall',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Controlada por Firewall?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='logos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Tiene Logos Institucionales?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='online_help',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='Ayudas en linea'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='parametrizable',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Es parametrizable?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='responsive',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Es responsive (para el caso de los sistemas web)? '),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Tiene esquema de roles y perfiles?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='ssl',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Tiene certificado de sitio seguro? '),
        ),
        migrations.AlterField(
            model_name='inventario_software',
            name='observations',
            field=models.TextField(blank=True, max_length=500, verbose_name='Observaciones'),
        ),
    ]
