# Generated by Django 3.1.14 on 2022-03-01 18:21

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220301_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_software',
            name='admin_user',
            field=models.CharField(blank=True, max_length=258, verbose_name='Usuario administrador'),
        ),
        migrations.AlterField(
            model_name='inventario_software',
            name='auditoria',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Tiene esquema de auditorías?'),
        ),
        migrations.AlterField(
            model_name='inventario_software',
            name='criterios',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Aplica criterios de usabilidad y accesibilidad?'),
        ),
        migrations.AlterField(
            model_name='inventario_software',
            name='responsive',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Es responsive (para el caso de los sistemas web)?'),
        ),
        migrations.AlterField(
            model_name='inventario_software',
            name='ssl',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Tiene certificado de sitio seguro?'),
        ),
        migrations.CreateModel(
            name='WebService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_service', models.CharField(blank=True, max_length=258, verbose_name='Descripcion')),
                ('url', models.CharField(blank=True, max_length=258, verbose_name='Url')),
                ('inventary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventario_software')),
            ],
            options={
                'verbose_name': 'Web Service',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=258, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=258, verbose_name='Description')),
                ('installed', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='Está Instalado')),
                ('observation', models.TextField(blank=True, max_length=500, verbose_name='Observacion')),
                ('inventary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventario_software')),
            ],
            options={
                'verbose_name': 'Modulos',
            },
        ),
    ]
