# Generated by Django 3.1.14 on 2022-03-01 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220301_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('description', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Version',
            },
        ),
        migrations.CreateModel(
            name='SoftwareRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(blank=True, max_length=500, verbose_name='Observaciones')),
                ('architecture', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.architecture', verbose_name='Arquitectura')),
                ('inventary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventario_software')),
                ('type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.os', verbose_name='Tipo')),
                ('version', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.version', verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Web Service',
            },
        ),
        migrations.CreateModel(
            name='BdRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mannager', models.CharField(blank=True, max_length=258, verbose_name='Manejador')),
                ('version', models.CharField(blank=True, max_length=258, verbose_name='Version')),
                ('port', models.CharField(blank=True, max_length=258, verbose_name='Puerto')),
                ('soft_req_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.softwarerequirements')),
            ],
            options={
                'verbose_name': 'De base de datos',
            },
        ),
        migrations.CreateModel(
            name='AppRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=258, verbose_name='Lenguaje')),
                ('version', models.CharField(blank=True, max_length=258, verbose_name='Version')),
                ('libraries', models.CharField(blank=True, max_length=258, verbose_name='Bibliotecas')),
                ('soft_req_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.softwarerequirements')),
            ],
            options={
                'verbose_name': 'De aplicacion',
            },
        ),
    ]
