# Generated by Django 3.1.14 on 2022-03-01 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220301_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='BdInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name_server', models.CharField(blank=True, max_length=258, verbose_name='Nombre Servidor de BD')),
                ('db_name', models.CharField(blank=True, max_length=258, verbose_name='Nombre BD')),
                ('user', models.CharField(blank=True, max_length=258, verbose_name='Usuario')),
                ('route', models.CharField(blank=True, max_length=258, verbose_name='Ruta')),
                ('disk_space', models.CharField(blank=True, max_length=258, verbose_name='Espacio en disco (actual)')),
                ('proyection', models.CharField(blank=True, max_length=258, verbose_name='Proyección a 3 años')),
                ('backup_policy', models.CharField(blank=True, max_length=258, verbose_name='Política de Backup')),
                ('db_location', models.CharField(blank=True, max_length=258, verbose_name='Ubicación de la DB')),
                ('observation', models.TextField(blank=True, max_length=500, verbose_name='Observaciones')),
                ('backup_method', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.backup_method', verbose_name='Método de Backup')),
                ('inventary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventario_software')),
                ('licence', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.db_licences', verbose_name='Licenciamiento de DB')),
                ('mannager', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.db_mannager', verbose_name='Manejador')),
                ('periodicity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.periodicity_backup', verbose_name='Periodicidad')),
                ('storage', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.storage', verbose_name='Medio de almacenamiento')),
            ],
            options={
                'verbose_name': 'INFORMACIÓN DE BASES DE DATOS ASOCIADA/S A LA APLICACIÓN',
            },
        ),
    ]
