# Generated by Django 3.1.14 on 2022-03-01 20:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bdinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_software',
            name='acta_choice1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se entregó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='acta_choice2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se aprobó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='acta_choice3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisico', 'Fisico'), ('Digital', 'Digital')], max_length=14, verbose_name='Medio'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='acta_location',
            field=models.CharField(blank=True, max_length=258, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='admin_manual_choice1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se entregó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='admin_manual_choice2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se aprobó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='admin_manual_choice3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisico', 'Fisico'), ('Digital', 'Digital')], max_length=14, verbose_name='Medio'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='admin_manual_location',
            field=models.CharField(blank=True, max_length=258, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='data_dic_choice1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se entregó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='data_dic_choice2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se aprobó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='data_dic_choice3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisico', 'Fisico'), ('Digital', 'Digital')], max_length=14, verbose_name='Medio'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='data_dic_location',
            field=models.CharField(blank=True, max_length=258, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='definition_choice1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se entregó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='definition_choice2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se aprobó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='definition_choice3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisico', 'Fisico'), ('Digital', 'Digital')], max_length=14, verbose_name='Medio'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='definition_location',
            field=models.CharField(blank=True, max_length=258, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='design_doc_choice1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se entregó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='design_doc_choice2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se aprobó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='design_doc_choice3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisico', 'Fisico'), ('Digital', 'Digital')], max_length=14, verbose_name='Medio'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='design_doc_location',
            field=models.CharField(blank=True, max_length=258, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='pers_doc_choice1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se entregó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='pers_doc_choice2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se aprobó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='pers_doc_choice3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisico', 'Fisico'), ('Digital', 'Digital')], max_length=14, verbose_name='Medio'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='pers_doc_location',
            field=models.CharField(blank=True, max_length=258, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='prod_plan_choice1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se entregó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='prod_plan_choice2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se aprobó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='prod_plan_choice3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisico', 'Fisico'), ('Digital', 'Digital')], max_length=14, verbose_name='Medio'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='prod_plan_location',
            field=models.CharField(blank=True, max_length=258, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='proyect_plan_choice1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se entregó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='proyect_plan_choice2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se aprobó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='proyect_plan_choice3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisico', 'Fisico'), ('Digital', 'Digital')], max_length=14, verbose_name='Medio'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='proyect_plan_location',
            field=models.CharField(blank=True, max_length=258, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='req_doc_choice1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se entregó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='req_doc_choice2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se aprobó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='req_doc_choice3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisico', 'Fisico'), ('Digital', 'Digital')], max_length=14, verbose_name='Medio'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='req_doc_location',
            field=models.CharField(blank=True, max_length=258, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='sec_manual_choice1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se entregó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='sec_manual_choice2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se aprobó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='sec_manual_choice3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisico', 'Fisico'), ('Digital', 'Digital')], max_length=14, verbose_name='Medio'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='sec_manual_location',
            field=models.CharField(blank=True, max_length=258, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='service_agr_choice1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se entregó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='service_agr_choice2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se aprobó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='service_agr_choice3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisico', 'Fisico'), ('Digital', 'Digital')], max_length=14, verbose_name='Medio'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='service_agr_location',
            field=models.CharField(blank=True, max_length=258, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='soft_arch_choice1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se entregó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='soft_arch_choice2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se aprobó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='soft_arch_choice3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisico', 'Fisico'), ('Digital', 'Digital')], max_length=14, verbose_name='Medio'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='soft_arch_location',
            field=models.CharField(blank=True, max_length=258, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='tec_manual_choice1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se entregó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='tec_manual_choice2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se aprobó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='tec_manual_choice3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisico', 'Fisico'), ('Digital', 'Digital')], max_length=14, verbose_name='Medio'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='tec_manual_location',
            field=models.CharField(blank=True, max_length=258, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='test_doc_choice1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se entregó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='test_doc_choice2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se aprobó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='test_doc_choice3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisico', 'Fisico'), ('Digital', 'Digital')], max_length=14, verbose_name='Medio'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='test_doc_location',
            field=models.CharField(blank=True, max_length=258, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='unit_test_doc_choice1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se entregó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='unit_test_doc_choice2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se aprobó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='unit_test_doc_choice3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisico', 'Fisico'), ('Digital', 'Digital')], max_length=14, verbose_name='Medio'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='unit_test_doc_location',
            field=models.CharField(blank=True, max_length=258, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='user_manual_choice1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se entregó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='user_manual_choice2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5, verbose_name='¿Se aprobó?'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='user_manual_choice3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisico', 'Fisico'), ('Digital', 'Digital')], max_length=14, verbose_name='Medio'),
        ),
        migrations.AddField(
            model_name='inventario_software',
            name='user_manual_location',
            field=models.CharField(blank=True, max_length=258, verbose_name='Ubicación'),
        ),
    ]
